export const seedSettings = {
  site_name: 'Sunwings Transport',
  phone: '647-526-5132',
  email: 'dispatch@sunwingstransport.ca',
  seo_title: 'Sunwings Transport | Moving, Delivery & Commercial Transport',
  seo_description: 'Residential moving, furniture delivery, junk removal, commercial transport and warehouse support across Toronto, the GTA, Hamilton and Niagara.',
  seo_image: '',
  google_site_verification: '',
  hero_title: 'Moving & delivery, done right.',
  hero_description: 'Residential moves, furniture delivery, junk removal and commercial transport across Toronto, the GTA, Hamilton and Niagara. Careful crews, upfront pricing, no surprises.',
  hero_image: '',
  hero_cta_label: 'View Services',
  hero_cta_url: '/services',
};

export const seedServices = [
  {
    id: 'seed-service-1',
    slug: 'residential-moving',
    title: 'Residential Moving',
    eyebrow: 'Residential Services',
    hero_title: 'Residential Moving Across Toronto, GTA, Hamilton & Niagara',
    hero_description: 'Apartment, condo, house, basement, student and small moves with careful loading, protection and placement.',
    banner_image: '',
    banner_alt: 'Sunwings Transport residential moving',
    intro: 'Sunwings Transport handles practical residential moves of all sizes with careful loading, furniture protection and flexible scheduling.',
    body_html: '<h2>Moving help built around the job</h2><p>From one-bedroom apartments to homes and downsizing moves, Sunwings can provide loading, transportation, furniture protection, disassembly, reassembly and placement at the destination.</p>',
    bullets: ['Apartment and condo moves','House and basement moves','Small moves and single-room moves','Furniture protection and wrapping','Disassembly and reassembly','Loading, unloading and placement'],
    cta_title: 'Planning a residential move?',
    cta_text: 'Tell us what is moving, where it is going and when you need it done.',
    seo_title: 'Residential Movers Toronto, GTA, Hamilton & Niagara | Sunwings Transport',
    seo_description: 'Residential moving services across Toronto, the GTA, Hamilton and Niagara including apartments, condos, houses, furniture protection, loading and placement.',
    og_image: '',
    status: 'published',
    sort_order: 1,
  },
  {
    id: 'seed-service-2',
    slug: 'commercial-transport',
    title: 'Commercial Transport',
    eyebrow: 'Business Services',
    hero_title: 'Commercial Transport & Business Moving',
    hero_description: 'Transport, relocation and recurring support for businesses, retailers, warehouses, contractors and property managers.',
    banner_image: '',
    banner_alt: 'Sunwings Transport commercial transport',
    intro: 'Sunwings provides flexible commercial transport for one-time projects and ongoing business needs.',
    body_html: '<h2>Built for ongoing business work</h2><p>Commercial work can include equipment transport, office and retail moves, inventory movement, scheduled deliveries and recurring routes.</p>',
    bullets: ['Office and retail moves','Equipment transport','Inventory movement','Scheduled business deliveries','Recurring routes','Project-based transport'],
    cta_title: 'Need recurring transport?',
    cta_text: 'Talk to Sunwings about ongoing or contract work.',
    seo_title: 'Commercial Transport Toronto, GTA, Hamilton & Niagara | Sunwings Transport',
    seo_description: 'Commercial transport, business moving, inventory movement and scheduled delivery services across Toronto, the GTA, Hamilton and Niagara.',
    og_image: '',
    status: 'published',
    sort_order: 2,
  },
  {
    id: 'seed-service-3',
    slug: 'furniture-delivery',
    title: 'Furniture Delivery',
    eyebrow: 'Pickup & Delivery',
    hero_title: 'Furniture Pickup & Delivery',
    hero_description: 'Careful furniture pickup and delivery for homes, retailers, marketplace purchases and businesses.',
    banner_image: '',
    banner_alt: 'Furniture delivery by Sunwings Transport',
    intro: 'Sunwings handles single-item and multi-item furniture deliveries with careful loading and placement.',
    body_html: '<h2>Delivery without the hassle</h2><p>Furniture can be picked up from retailers, private sellers, storage locations or another property and delivered where it needs to go.</p>',
    bullets: ['Single-item delivery','Multi-item delivery','Retail pickup','Marketplace pickup','Furniture protection','Room placement'],
    cta_title: 'Have something that needs delivery?',
    cta_text: 'Send the pickup and delivery details for a quote.',
    seo_title: 'Furniture Delivery Toronto, GTA, Hamilton & Niagara | Sunwings Transport',
    seo_description: 'Furniture pickup and delivery across Toronto, the GTA, Hamilton and Niagara for homes, retailers and marketplace purchases.',
    og_image: '',
    status: 'published',
    sort_order: 3,
  },
  {
    id: 'seed-service-4',
    slug: 'packing-protection',
    title: 'Packing & Protection',
    eyebrow: 'Move Preparation',
    hero_title: 'Packing, Wrapping & Furniture Protection',
    hero_description: 'Moving blankets, stretch wrap, mattress protection and preparation for safer transport.',
    banner_image: '',
    banner_alt: 'Furniture wrapping and protection',
    intro: 'Proper preparation protects furniture and helps the move run more efficiently.',
    body_html: '<h2>Protect before transport</h2><p>Sunwings can help prepare furniture and larger items for moving using blankets, stretch wrap and practical protection methods.</p>',
    bullets: ['Moving blankets','Stretch wrap','Mattress protection','Furniture preparation','Disassembly support','Reassembly support'],
    cta_title: 'Need packing or protection included?',
    cta_text: 'Add it to your moving or delivery request.',
    seo_title: 'Packing & Furniture Protection Toronto, GTA, Hamilton & Niagara | Sunwings Transport',
    seo_description: 'Packing, furniture wrapping, mattress protection, disassembly and reassembly for moves across Toronto, the GTA, Hamilton and Niagara.',
    og_image: '',
    status: 'published',
    sort_order: 4,
  },
  {
    id: 'seed-service-5',
    slug: 'warehouse-container-unloading',
    title: 'Warehouse & Container Unloading',
    eyebrow: 'Warehouse Support',
    hero_title: 'Warehouse, Loading & Container Unloading Support',
    hero_description: 'Hands-on transport and labour support for warehouse transfers, loading, unloading and container work.',
    banner_image: '',
    banner_alt: 'Warehouse and container unloading',
    intro: 'Sunwings supports businesses that need transportation combined with practical loading and unloading labour.',
    body_html: '<h2>Transport plus labour</h2><p>Warehouse support can include container unloading, inventory movement, transfers between locations and placement after delivery.</p>',
    bullets: ['Container unloading','Warehouse transfers','Inventory movement','Loading and unloading','Placement support','Business transport'],
    cta_title: 'Need warehouse or container support?',
    cta_text: 'Describe the job and the labour required.',
    seo_title: 'Container Unloading & Warehouse Labour Toronto, GTA, Hamilton & Niagara | Sunwings',
    seo_description: 'Container unloading, warehouse transfers, inventory movement and labour support across Toronto, the GTA, Hamilton and Niagara.',
    og_image: '',
    status: 'published',
    sort_order: 5,
  },
  {
    id: 'seed-service-6',
    slug: 'junk-removal',
    title: 'Junk Removal',
    eyebrow: 'Junk Removal',
    hero_title: 'Junk removal, done in one trip.',
    hero_description: 'Old furniture, appliances and clean-outs hauled away so you do not have to.',
    banner_image: 'https://sunwingstransport.ca/wp-content/uploads/2026/02/cargo-van-driveway1.png',
    banner_alt: 'Sunwings Transport junk removal',
    intro: 'Clearing a basement, garage or whole unit? We load it, haul it and leave the space ready for what is next.',
    body_html: '<h2>Junk removal for moves and clean-outs</h2><p>Sunwings can remove old furniture, appliances and non-hazardous clean-out material from homes, rentals and business spaces.</p>',
    bullets: ['Furniture removal','Appliance removal','Basement & garage clean-outs','Move-out clean-outs','Renovation debris','Responsible disposal'],
    cta_title: 'Need junk removed?',
    cta_text: 'Tell us what needs to go and where it is located.',
    seo_title: 'Junk Removal Toronto, GTA, Hamilton & Niagara | Sunwings',
    seo_description: 'Furniture removal, appliance removal and clean-out hauling across Toronto, the GTA, Hamilton and Niagara.',
    og_image: '',
    status: 'published',
    sort_order: 6,
  },
];

export const seedLocations = [
  {
    id: 'seed-location-1',
    slug: 'toronto',
    title: 'Toronto',
    region: 'Toronto & GTA',
    eyebrow: 'Toronto Moving & Transport',
    hero_title: 'Toronto Moving, Delivery & Commercial Transport',
    hero_description: 'Residential moving, furniture delivery, commercial transport and labour services throughout Toronto.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Toronto',
    intro: 'Toronto moving and transport services for residential and business customers, including apartment, condo, home, furniture delivery and commercial work.',
    body_html: '<h2>Moving and transport in Toronto</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in Toronto and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in Toronto?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Toronto Movers, Delivery & Commercial Transport | Sunwings',
    seo_description: 'Moving, furniture delivery, commercial transport and labour services throughout Toronto.',
    og_image: '',
    status: 'published',
    sort_order: 1,
  },
  {
    id: 'seed-location-2',
    slug: 'scarborough',
    title: 'Scarborough',
    region: 'Toronto & GTA',
    eyebrow: 'Scarborough Moving & Transport',
    hero_title: 'Scarborough Moving, Delivery & Commercial Transport',
    hero_description: 'Residential and commercial transport services throughout Scarborough.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Scarborough',
    intro: 'Sunwings provides moving, delivery and business transport throughout Scarborough and surrounding east Toronto communities.',
    body_html: '<h2>Moving and transport in Scarborough</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in Scarborough and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in Scarborough?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Scarborough Movers & Delivery | Sunwings Transport',
    seo_description: 'Moving, delivery and commercial transport services in Scarborough.',
    og_image: '',
    status: 'published',
    sort_order: 2,
  },
  {
    id: 'seed-location-3',
    slug: 'north-york',
    title: 'North York',
    region: 'Toronto & GTA',
    eyebrow: 'North York Moving & Transport',
    hero_title: 'North York Moving, Delivery & Commercial Transport',
    hero_description: 'Moving, furniture delivery and business transport throughout North York.',
    banner_image: '',
    banner_alt: 'Sunwings Transport North York',
    intro: 'Sunwings supports residential moves, deliveries and commercial transport throughout North York.',
    body_html: '<h2>Moving and transport in North York</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in North York and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in North York?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'North York Movers & Delivery | Sunwings Transport',
    seo_description: 'Moving, delivery and commercial transport services in North York.',
    og_image: '',
    status: 'published',
    sort_order: 3,
  },
  {
    id: 'seed-location-4',
    slug: 'etobicoke',
    title: 'Etobicoke',
    region: 'Toronto & GTA',
    eyebrow: 'Etobicoke Moving & Transport',
    hero_title: 'Etobicoke Moving, Delivery & Commercial Transport',
    hero_description: 'Residential moving, delivery and commercial transport throughout Etobicoke.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Etobicoke',
    intro: 'Sunwings provides practical moving and transport services throughout Etobicoke and west Toronto.',
    body_html: '<h2>Moving and transport in Etobicoke</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in Etobicoke and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in Etobicoke?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Etobicoke Movers & Delivery | Sunwings Transport',
    seo_description: 'Moving, delivery and commercial transport services in Etobicoke.',
    og_image: '',
    status: 'published',
    sort_order: 4,
  },
  {
    id: 'seed-location-5',
    slug: 'mississauga',
    title: 'Mississauga',
    region: 'Peel Region',
    eyebrow: 'Mississauga Moving & Transport',
    hero_title: 'Mississauga Moving, Delivery & Commercial Transport',
    hero_description: 'Moving, delivery and business transport services throughout Mississauga.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Mississauga',
    intro: 'Sunwings serves residential and commercial customers throughout Mississauga with moving, delivery and labour support.',
    body_html: '<h2>Moving and transport in Mississauga</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in Mississauga and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in Mississauga?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Mississauga Movers & Delivery | Sunwings Transport',
    seo_description: 'Moving, delivery and commercial transport services in Mississauga.',
    og_image: '',
    status: 'published',
    sort_order: 5,
  },
  {
    id: 'seed-location-6',
    slug: 'brampton',
    title: 'Brampton',
    region: 'Peel Region',
    eyebrow: 'Brampton Moving & Transport',
    hero_title: 'Brampton Moving, Delivery & Commercial Transport',
    hero_description: 'Residential and commercial moving and transport services throughout Brampton.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Brampton',
    intro: 'Sunwings provides moving, furniture delivery and business transport throughout Brampton.',
    body_html: '<h2>Moving and transport in Brampton</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in Brampton and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in Brampton?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Brampton Movers & Delivery | Sunwings Transport',
    seo_description: 'Moving, delivery and commercial transport services in Brampton.',
    og_image: '',
    status: 'published',
    sort_order: 6,
  },
  {
    id: 'seed-location-7',
    slug: 'vaughan',
    title: 'Vaughan',
    region: 'York Region',
    eyebrow: 'Vaughan Moving & Transport',
    hero_title: 'Vaughan Moving, Delivery & Commercial Transport',
    hero_description: 'Moving, delivery and commercial transport throughout Vaughan.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Vaughan',
    intro: 'Sunwings supports residential customers and businesses throughout Vaughan.',
    body_html: '<h2>Moving and transport in Vaughan</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in Vaughan and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in Vaughan?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Vaughan Movers & Delivery | Sunwings Transport',
    seo_description: 'Moving, delivery and commercial transport services in Vaughan.',
    og_image: '',
    status: 'published',
    sort_order: 7,
  },
  {
    id: 'seed-location-8',
    slug: 'markham',
    title: 'Markham',
    region: 'York Region',
    eyebrow: 'Markham Moving & Transport',
    hero_title: 'Markham Moving, Delivery & Commercial Transport',
    hero_description: 'Moving, delivery and commercial transport throughout Markham.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Markham',
    intro: 'Sunwings supports residential customers and businesses throughout Markham.',
    body_html: '<h2>Moving and transport in Markham</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in Markham and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in Markham?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Markham Movers & Delivery | Sunwings Transport',
    seo_description: 'Moving, delivery and commercial transport services in Markham.',
    og_image: '',
    status: 'published',
    sort_order: 8,
  },
  {
    id: 'seed-location-9',
    slug: 'richmond-hill',
    title: 'Richmond Hill',
    region: 'York Region',
    eyebrow: 'Richmond Hill Moving & Transport',
    hero_title: 'Richmond Hill Moving, Delivery & Commercial Transport',
    hero_description: 'Moving, delivery and commercial transport throughout Richmond Hill.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Richmond Hill',
    intro: 'Sunwings supports residential customers and businesses throughout Richmond Hill.',
    body_html: '<h2>Moving and transport in Richmond Hill</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in Richmond Hill and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in Richmond Hill?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Richmond Hill Movers & Delivery | Sunwings Transport',
    seo_description: 'Moving, delivery and commercial transport services in Richmond Hill.',
    og_image: '',
    status: 'published',
    sort_order: 9,
  },
  {
    id: 'seed-location-10',
    slug: 'oakville',
    title: 'Oakville',
    region: 'Halton Region',
    eyebrow: 'Oakville Moving & Transport',
    hero_title: 'Oakville Moving, Delivery & Commercial Transport',
    hero_description: 'Moving, furniture delivery and business transport throughout Oakville.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Oakville',
    intro: 'Sunwings provides residential and commercial transport throughout Oakville.',
    body_html: '<h2>Moving and transport in Oakville</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in Oakville and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in Oakville?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Oakville Movers & Delivery | Sunwings Transport',
    seo_description: 'Moving, delivery and commercial transport services in Oakville.',
    og_image: '',
    status: 'published',
    sort_order: 10,
  },
  {
    id: 'seed-location-11',
    slug: 'burlington',
    title: 'Burlington',
    region: 'Halton Region',
    eyebrow: 'Burlington Moving & Transport',
    hero_title: 'Burlington Moving, Delivery & Commercial Transport',
    hero_description: 'Moving, furniture delivery and business transport throughout Burlington.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Burlington',
    intro: 'Sunwings provides residential and commercial transport throughout Burlington.',
    body_html: '<h2>Moving and transport in Burlington</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in Burlington and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in Burlington?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Burlington Movers & Delivery | Sunwings Transport',
    seo_description: 'Moving, delivery and commercial transport services in Burlington.',
    og_image: '',
    status: 'published',
    sort_order: 11,
  },
  {
    id: 'seed-location-12',
    slug: 'milton',
    title: 'Milton',
    region: 'Halton Region',
    eyebrow: 'Milton Moving & Transport',
    hero_title: 'Milton Moving, Delivery & Commercial Transport',
    hero_description: 'Moving, delivery and commercial transport throughout Milton.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Milton',
    intro: 'Sunwings provides residential and commercial moving and transport services throughout Milton.',
    body_html: '<h2>Moving and transport in Milton</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in Milton and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in Milton?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Milton Movers & Delivery | Sunwings Transport',
    seo_description: 'Moving, delivery and commercial transport services in Milton.',
    og_image: '',
    status: 'published',
    sort_order: 12,
  },
  {
    id: 'seed-location-13',
    slug: 'hamilton',
    title: 'Hamilton',
    region: 'Hamilton Region',
    eyebrow: 'Hamilton Moving & Transport',
    hero_title: 'Hamilton Moving, Delivery & Commercial Transport',
    hero_description: 'Residential moving, furniture delivery, business transport, warehouse support and labour throughout Hamilton.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Hamilton',
    intro: 'Sunwings provides practical moving, delivery and commercial transport services throughout Hamilton.',
    body_html: '<h2>Moving and transport in Hamilton</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in Hamilton and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in Hamilton?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Hamilton Movers, Delivery & Commercial Transport | Sunwings',
    seo_description: 'Moving, furniture delivery, commercial transport, warehouse support and junk removal throughout Hamilton.',
    og_image: '',
    status: 'published',
    sort_order: 13,
  },
  {
    id: 'seed-location-14',
    slug: 'stoney-creek',
    title: 'Stoney Creek',
    region: 'Hamilton Region',
    eyebrow: 'Stoney Creek Moving & Transport',
    hero_title: 'Stoney Creek Moving, Delivery & Commercial Transport',
    hero_description: 'Moving, delivery and commercial transport throughout Stoney Creek.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Stoney Creek',
    intro: 'Sunwings provides residential moving, furniture delivery and business transport throughout Stoney Creek.',
    body_html: '<h2>Moving and transport in Stoney Creek</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in Stoney Creek and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in Stoney Creek?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Stoney Creek Movers & Delivery | Sunwings Transport',
    seo_description: 'Moving, delivery and commercial transport services in Stoney Creek.',
    og_image: '',
    status: 'published',
    sort_order: 14,
  },
  {
    id: 'seed-location-15',
    slug: 'ancaster',
    title: 'Ancaster',
    region: 'Hamilton Region',
    eyebrow: 'Ancaster Moving & Transport',
    hero_title: 'Ancaster Moving, Delivery & Commercial Transport',
    hero_description: 'Moving, delivery and commercial transport throughout Ancaster.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Ancaster',
    intro: 'Sunwings provides residential moving, furniture delivery and business transport throughout Ancaster.',
    body_html: '<h2>Moving and transport in Ancaster</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in Ancaster and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in Ancaster?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Ancaster Movers & Delivery | Sunwings Transport',
    seo_description: 'Moving, delivery and commercial transport services in Ancaster.',
    og_image: '',
    status: 'published',
    sort_order: 15,
  },
  {
    id: 'seed-location-16',
    slug: 'dundas',
    title: 'Dundas',
    region: 'Hamilton Region',
    eyebrow: 'Dundas Moving & Transport',
    hero_title: 'Dundas Moving, Delivery & Commercial Transport',
    hero_description: 'Moving, delivery and commercial transport throughout Dundas.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Dundas',
    intro: 'Sunwings provides residential moving, furniture delivery and business transport throughout Dundas.',
    body_html: '<h2>Moving and transport in Dundas</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in Dundas and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in Dundas?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Dundas Movers & Delivery | Sunwings Transport',
    seo_description: 'Moving, delivery and commercial transport services in Dundas.',
    og_image: '',
    status: 'published',
    sort_order: 16,
  },
  {
    id: 'seed-location-17',
    slug: 'waterdown',
    title: 'Waterdown',
    region: 'Hamilton Region',
    eyebrow: 'Waterdown Moving & Transport',
    hero_title: 'Waterdown Moving, Delivery & Commercial Transport',
    hero_description: 'Moving, delivery and commercial transport throughout Waterdown.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Waterdown',
    intro: 'Sunwings provides residential moving, furniture delivery and business transport throughout Waterdown.',
    body_html: '<h2>Moving and transport in Waterdown</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in Waterdown and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in Waterdown?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Waterdown Movers & Delivery | Sunwings Transport',
    seo_description: 'Moving, delivery and commercial transport services in Waterdown.',
    og_image: '',
    status: 'published',
    sort_order: 17,
  },
  {
    id: 'seed-location-18',
    slug: 'grimsby',
    title: 'Grimsby',
    region: 'Niagara Region',
    eyebrow: 'Grimsby Moving & Transport',
    hero_title: 'Grimsby Moving, Delivery & Commercial Transport',
    hero_description: 'Moving, delivery and commercial transport throughout Grimsby.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Grimsby',
    intro: 'Sunwings serves residential customers and businesses throughout Grimsby.',
    body_html: '<h2>Moving and transport in Grimsby</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in Grimsby and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in Grimsby?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Grimsby Movers & Delivery | Sunwings Transport',
    seo_description: 'Moving, delivery and commercial transport services in Grimsby.',
    og_image: '',
    status: 'published',
    sort_order: 18,
  },
  {
    id: 'seed-location-19',
    slug: 'st-catharines',
    title: 'St. Catharines',
    region: 'Niagara Region',
    eyebrow: 'St. Catharines Moving & Transport',
    hero_title: 'St. Catharines Moving, Delivery & Commercial Transport',
    hero_description: 'Moving, delivery and commercial transport throughout St. Catharines.',
    banner_image: '',
    banner_alt: 'Sunwings Transport St. Catharines',
    intro: 'Sunwings serves residential customers and businesses throughout St. Catharines.',
    body_html: '<h2>Moving and transport in St. Catharines</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in St. Catharines and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in St. Catharines?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'St. Catharines Movers & Delivery | Sunwings Transport',
    seo_description: 'Moving, delivery and commercial transport services in St. Catharines.',
    og_image: '',
    status: 'published',
    sort_order: 19,
  },
  {
    id: 'seed-location-20',
    slug: 'niagara-falls',
    title: 'Niagara Falls',
    region: 'Niagara Region',
    eyebrow: 'Niagara Falls Moving & Transport',
    hero_title: 'Niagara Falls Moving, Delivery & Commercial Transport',
    hero_description: 'Moving, delivery and commercial transport throughout Niagara Falls.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Niagara Falls',
    intro: 'Sunwings serves residential customers and businesses throughout Niagara Falls.',
    body_html: '<h2>Moving and transport in Niagara Falls</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in Niagara Falls and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in Niagara Falls?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Niagara Falls Movers & Delivery | Sunwings Transport',
    seo_description: 'Moving, delivery and commercial transport services in Niagara Falls.',
    og_image: '',
    status: 'published',
    sort_order: 20,
  },
  {
    id: 'seed-location-21',
    slug: 'welland',
    title: 'Welland',
    region: 'Niagara Region',
    eyebrow: 'Welland Moving & Transport',
    hero_title: 'Welland Moving, Delivery & Commercial Transport',
    hero_description: 'Moving, delivery and commercial transport throughout Welland.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Welland',
    intro: 'Sunwings serves residential customers and businesses throughout Welland.',
    body_html: '<h2>Moving and transport in Welland</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in Welland and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in Welland?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Welland Movers & Delivery | Sunwings Transport',
    seo_description: 'Moving, delivery and commercial transport services in Welland.',
    og_image: '',
    status: 'published',
    sort_order: 21,
  },
  {
    id: 'seed-location-22',
    slug: 'thorold',
    title: 'Thorold',
    region: 'Niagara Region',
    eyebrow: 'Thorold Moving & Transport',
    hero_title: 'Thorold Moving, Delivery & Commercial Transport',
    hero_description: 'Moving, delivery and commercial transport throughout Thorold.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Thorold',
    intro: 'Sunwings serves residential customers and businesses throughout Thorold.',
    body_html: '<h2>Moving and transport in Thorold</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in Thorold and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in Thorold?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Thorold Movers & Delivery | Sunwings Transport',
    seo_description: 'Moving, delivery and commercial transport services in Thorold.',
    og_image: '',
    status: 'published',
    sort_order: 22,
  },
  {
    id: 'seed-location-23',
    slug: 'fort-erie',
    title: 'Fort Erie',
    region: 'Niagara Region',
    eyebrow: 'Fort Erie Moving & Transport',
    hero_title: 'Fort Erie Moving, Delivery & Commercial Transport',
    hero_description: 'Moving, delivery and commercial transport throughout Fort Erie.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Fort Erie',
    intro: 'Sunwings serves residential customers and businesses throughout Fort Erie.',
    body_html: '<h2>Moving and transport in Fort Erie</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in Fort Erie and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in Fort Erie?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Fort Erie Movers & Delivery | Sunwings Transport',
    seo_description: 'Moving, delivery and commercial transport services in Fort Erie.',
    og_image: '',
    status: 'published',
    sort_order: 23,
  },
  {
    id: 'seed-location-24',
    slug: 'lincoln',
    title: 'Lincoln',
    region: 'Niagara Region',
    eyebrow: 'Lincoln Moving & Transport',
    hero_title: 'Lincoln Moving, Delivery & Commercial Transport',
    hero_description: 'Moving, delivery and commercial transport throughout Lincoln.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Lincoln',
    intro: 'Sunwings serves residential customers and businesses throughout Lincoln.',
    body_html: '<h2>Moving and transport in Lincoln</h2><p>Sunwings provides residential moving, furniture delivery, commercial transport and junk removal in Lincoln and nearby communities.</p>',
    neighbourhoods: [],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','junk-removal'],
    faq: [],
    cta_title: 'Need service in Lincoln?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Lincoln Movers & Delivery | Sunwings Transport',
    seo_description: 'Moving, delivery and commercial transport services in Lincoln.',
    og_image: '',
    status: 'published',
    sort_order: 24,
  }
];
