export const seedSettings = {
  phone: '647-526-5132',
  email: 'dispatch@sunwingstransport.ca',
  hero_title: 'Hamilton & Niagara Moving, Delivery & Commercial Transport',
  hero_description: 'Professional residential moving, furniture delivery, commercial transport, warehouse support and general labour across Hamilton and the Niagara Region.',
  hero_image: '',
  hero_cta_label: 'View Services',
  hero_cta_url: '/services',
};

export const seedServices = [
  {
    id: 'seed-service-1',
    slug: 'residential-moving',
    title: 'Residential Moving',
    eyebrow: 'Residential Services',
    hero_title: 'Residential Moving Across Hamilton & Niagara',
    hero_description: 'Apartment, condo, house, basement, student and small moves with careful loading, protection and placement.',
    banner_image: '',
    banner_alt: 'Sunwings Transport residential moving',
    intro: 'Sunwings Transport handles practical residential moves of all sizes with careful loading, furniture protection and flexible scheduling.',
    body_html: '<h2>Moving help built around the job</h2><p>From one-bedroom apartments to homes and downsizing moves, Sunwings can provide loading, transportation, furniture protection, disassembly, reassembly and placement at the destination.</p>',
    bullets: ['Apartment and condo moves','House and basement moves','Small moves and single-room moves','Furniture protection and wrapping','Disassembly and reassembly','Loading, unloading and placement'],
    cta_title: 'Planning a residential move?',
    cta_text: 'Tell us what is moving, where it is going and when you need it done.',
    seo_title: 'Residential Movers Hamilton & Niagara | Sunwings Transport',
    seo_description: 'Residential moving services across Hamilton and Niagara including apartments, condos, houses, furniture protection, loading and placement.',
    og_image: '',
    status: 'published',
    sort_order: 1,
  },
  {
    id: 'seed-service-2',
    slug: 'commercial-transport',
    title: 'Commercial & Business Transport',
    eyebrow: 'Business Services',
    hero_title: 'Commercial Transport & Business Moving',
    hero_description: 'Transport, relocation and recurring support for businesses, retailers, warehouses, contractors and property managers.',
    banner_image: '',
    banner_alt: 'Sunwings Transport commercial transport',
    intro: 'Sunwings provides flexible commercial transport for one-time projects and ongoing business needs.',
    body_html: '<h2>Built for ongoing business work</h2><p>Commercial work can include equipment transport, office and retail moves, inventory movement, scheduled deliveries and recurring routes.</p>',
    bullets: ['Office and retail moves','Equipment transport','Inventory movement','Scheduled business deliveries','Recurring routes','Project-based transport'],
    cta_title: 'Need recurring transport?',
    cta_text: 'Talk to Sunwings about ongoing or contract work.',
    seo_title: 'Commercial Transport Hamilton & Niagara | Sunwings Transport',
    seo_description: 'Commercial transport, business moving, inventory movement and scheduled delivery services across Hamilton and Niagara.',
    og_image: '',
    status: 'published',
    sort_order: 2,
  },
  {
    id: 'seed-service-3',
    slug: 'furniture-delivery',
    title: 'Furniture Delivery',
    eyebrow: 'Pickup & Delivery',
    hero_title: 'Furniture Pickup & Delivery',
    hero_description: 'Careful furniture pickup and delivery for homes, retailers, marketplace purchases and businesses.',
    banner_image: '',
    banner_alt: 'Furniture delivery by Sunwings Transport',
    intro: 'Sunwings handles single-item and multi-item furniture deliveries with careful loading and placement.',
    body_html: '<h2>Delivery without the hassle</h2><p>Furniture can be picked up from retailers, private sellers, storage locations or another property and delivered where it needs to go.</p>',
    bullets: ['Single-item delivery','Multi-item delivery','Retail pickup','Marketplace pickup','Furniture protection','Room placement'],
    cta_title: 'Have something that needs delivery?',
    cta_text: 'Send the pickup and delivery details for a quote.',
    seo_title: 'Furniture Delivery Hamilton & Niagara | Sunwings Transport',
    seo_description: 'Furniture pickup and delivery across Hamilton and Niagara for homes, retailers and marketplace purchases.',
    og_image: '',
    status: 'published',
    sort_order: 3,
  },
  {
    id: 'seed-service-4',
    slug: 'packing-protection',
    title: 'Packing & Furniture Protection',
    eyebrow: 'Move Preparation',
    hero_title: 'Packing, Wrapping & Furniture Protection',
    hero_description: 'Moving blankets, stretch wrap, mattress protection and preparation for safer transport.',
    banner_image: '',
    banner_alt: 'Furniture wrapping and protection',
    intro: 'Proper preparation protects furniture and helps the move run more efficiently.',
    body_html: '<h2>Protect before transport</h2><p>Sunwings can help prepare furniture and larger items for moving using blankets, stretch wrap and practical protection methods.</p>',
    bullets: ['Moving blankets','Stretch wrap','Mattress protection','Furniture preparation','Disassembly support','Reassembly support'],
    cta_title: 'Need packing or protection included?',
    cta_text: 'Add it to your moving or delivery request.',
    seo_title: 'Packing & Furniture Protection Hamilton | Sunwings Transport',
    seo_description: 'Packing, furniture wrapping, mattress protection, disassembly and reassembly for moves in Hamilton and Niagara.',
    og_image: '',
    status: 'published',
    sort_order: 4,
  },
  {
    id: 'seed-service-5',
    slug: 'warehouse-container-unloading',
    title: 'Warehouse & Container Unloading',
    eyebrow: 'Warehouse Support',
    hero_title: 'Warehouse, Loading & Container Unloading Support',
    hero_description: 'Hands-on transport and labour support for warehouse transfers, loading, unloading and container work.',
    banner_image: '',
    banner_alt: 'Warehouse and container unloading',
    intro: 'Sunwings supports businesses that need transportation combined with practical loading and unloading labour.',
    body_html: '<h2>Transport plus labour</h2><p>Warehouse support can include container unloading, inventory movement, transfers between locations and placement after delivery.</p>',
    bullets: ['Container unloading','Warehouse transfers','Inventory movement','Loading and unloading','Placement support','Business transport'],
    cta_title: 'Need warehouse or container support?',
    cta_text: 'Describe the job and the labour required.',
    seo_title: 'Container Unloading & Warehouse Labour Hamilton | Sunwings',
    seo_description: 'Container unloading, warehouse transfers, inventory movement and labour support across Hamilton and Niagara.',
    og_image: '',
    status: 'published',
    sort_order: 5,
  },
  {
    id: 'seed-service-6',
    slug: 'general-labour',
    title: 'General Labour',
    eyebrow: 'Labour Support',
    hero_title: 'General Labour for Moving, Loading & Business Jobs',
    hero_description: 'Extra hands for lifting, loading, unloading, placement and transport-related commercial work.',
    banner_image: '',
    banner_alt: 'General labour and loading support',
    intro: 'Some jobs need labour even when a full move is not required. Sunwings can provide transport-related hands-on support.',
    body_html: '<h2>Extra labour when the job needs it</h2><p>General labour can support loading, unloading, lifting, placement, warehouse work and other practical transport-related tasks.</p>',
    bullets: ['Loading help','Unloading help','Lifting and placement','Warehouse labour','Commercial job support','Transport-related labour'],
    cta_title: 'Need extra hands?',
    cta_text: 'Tell us what the job involves and how much help you need.',
    seo_title: 'General Labour Hamilton & Niagara | Sunwings Transport',
    seo_description: 'General labour for loading, unloading, placement, warehouse and transport-related work across Hamilton and Niagara.',
    og_image: '',
    status: 'published',
    sort_order: 6,
  },
];

export const seedLocations = [
  {
    id: 'seed-location-1',
    slug: 'hamilton',
    title: 'Hamilton',
    region: 'Hamilton Region',
    eyebrow: 'Hamilton Moving & Transport',
    hero_title: 'Hamilton Moving, Delivery & Commercial Transport',
    hero_description: 'Residential moving, furniture delivery, business transport, warehouse support and labour throughout Hamilton.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Hamilton',
    intro: 'Sunwings provides practical moving, delivery and commercial transport services throughout Hamilton and surrounding communities.',
    body_html: '<h2>Moving and transport across Hamilton</h2><p>Service is available for residential customers and businesses, with routes and job support throughout Hamilton, Stoney Creek, Ancaster, Dundas, Waterdown and Binbrook.</p>',
    neighbourhoods: ['Hamilton','Stoney Creek','Ancaster','Dundas','Waterdown','Binbrook'],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','general-labour'],
    faq: [
      { question: 'Do you serve Stoney Creek and Ancaster?', answer: 'Yes. Hamilton service includes Stoney Creek, Ancaster and surrounding Hamilton communities.' },
      { question: 'Do you handle business work?', answer: 'Yes. Commercial transport, warehouse support, deliveries and recurring work are available.' }
    ],
    cta_title: 'Need service in Hamilton?',
    cta_text: 'Send the pickup, destination, job type and preferred date.',
    seo_title: 'Hamilton Movers, Delivery & Commercial Transport | Sunwings',
    seo_description: 'Moving, furniture delivery, commercial transport, warehouse support and general labour across Hamilton, Stoney Creek, Ancaster and nearby areas.',
    og_image: '',
    status: 'published',
    sort_order: 1,
  },
  {
    id: 'seed-location-2',
    slug: 'niagara',
    title: 'Niagara Region',
    region: 'Niagara Region',
    eyebrow: 'Niagara Moving & Transport',
    hero_title: 'Niagara Moving, Delivery & Commercial Transport',
    hero_description: 'Residential and business transport services throughout the Niagara Region.',
    banner_image: '',
    banner_alt: 'Sunwings Transport Niagara Region',
    intro: 'Sunwings serves residential and commercial customers across the Niagara Region with moving, delivery and labour support.',
    body_html: '<h2>Regional service across Niagara</h2><p>Sunwings can support moves and transport work in St. Catharines, Niagara Falls, Grimsby, Welland, Thorold, Fort Erie and surrounding communities.</p>',
    neighbourhoods: ['St. Catharines','Niagara Falls','Grimsby','Welland','Thorold','Fort Erie'],
    service_slugs: ['residential-moving','commercial-transport','furniture-delivery','packing-protection','warehouse-container-unloading','general-labour'],
    faq: [
      { question: 'Which Niagara communities do you serve?', answer: 'Service can include St. Catharines, Niagara Falls, Grimsby, Welland, Thorold, Fort Erie and nearby communities.' },
      { question: 'Can you move between Hamilton and Niagara?', answer: 'Yes. Hamilton-to-Niagara and Niagara-to-Hamilton jobs can be quoted.' }
    ],
    cta_title: 'Need service in Niagara?',
    cta_text: 'Tell us the locations, job type and date for a quote.',
    seo_title: 'Niagara Movers, Delivery & Commercial Transport | Sunwings',
    seo_description: 'Moving, delivery, commercial transport and labour services across St. Catharines, Niagara Falls, Grimsby, Welland and the Niagara Region.',
    og_image: '',
    status: 'published',
    sort_order: 2,
  },
];
